package org.example.DomainLayer.NotificationAggregate;

public enum NotificationType {
    PURCHASE_COMPLETED,
    EVENT_CANCELLED,
    EVENT_RESCHEDULED,
    ACTIVE_PURCHASE_EXPIRING,
    EVENT_SOLD_OUT,
    COMPANY_CLOSED_OR_FROZEN,
    COMPANY_REOPENED,
    ROLE_CHANGED,
    MANAGER_INVITATION_RECEIVED,
    OWNER_INVITATION_RECEIVED,
    MANAGER_PERMISSIONS_CHANGED,
    SYSTEM_OR_PRODUCER_MESSAGE,
    LOTTERY_WON,
    QUEUE_TURN_AVAILABLE,
    REFUND_COMPLETED,
    INQUIRY_RECEIVED,
    INQUIRY_ANSWERED,
    USER_SUSPENDED,
    USER_UNSUSPENDED
}