package org.example.ApplicationLayer;

import java.time.Instant;

/**
 * Immutable value object that represents one live JWT session for a user.
 *
 * <h2>Purpose</h2>
 * <p>{@link IActiveSessionRegistry} stores exactly one {@code ActiveSession}
 * per user. When a user logs in while an older session is still active,
 * the registry's {@code replaceSession} returns the displaced
 * {@code ActiveSession} so that {@link SessionService} can immediately
 * revoke its {@code jti} via {@link ITokenBlacklist}.
 *
 * <h2>Design notes</h2>
 * <ul>
 *   <li><b>Value Object (DDD)</b> — identity is structural: two
 *       {@code ActiveSession} instances with the same {@code jti} and
 *       {@code expiresAt} are considered equal. The compact record
 *       constructor enforces this automatically.</li>
 *   <li><b>Immutable</b> — records in Java are shallowly immutable;
 *       both fields ({@link String}, {@link Instant}) are themselves
 *       immutable, so no defensive copying is needed.</li>
 *   <li><b>No behaviour</b> — this class deliberately has no methods
 *       beyond the accessors generated by the record declaration.
 *       Business logic (expiry checking, revocation) belongs in
 *       {@link SessionService} and {@link ITokenBlacklist}.</li>
 * </ul>
 *
 * @param jti       the JWT ID claim ({@code jti}) that uniquely identifies
 *                  this token; must not be {@code null} or blank
 * @param expiresAt the instant at which the JWT expires; used by
 *                  {@link ITokenBlacklist#revoke} so the blacklist entry
 *                  auto-evicts when the token itself would expire anyway;
 *                  must not be {@code null}
 */
public record ActiveSession(String jti, Instant expiresAt) {

    /**
     * Compact canonical constructor — validates invariants before the
     * record fields are assigned, so an {@code ActiveSession} is always
     * in a legal state.
     */
    public ActiveSession {
        if (jti == null || jti.isBlank()) {
            throw new IllegalArgumentException("ActiveSession.jti must not be null or blank");
        }
        if (expiresAt == null) {
            throw new IllegalArgumentException("ActiveSession.expiresAt must not be null");
        }
    }
}
